name: build-scan-deploy

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  APP_NAME: hello-ecs
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build_scan_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-oidc-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECR URL
        run: |
          echo "ECR_URL=$(aws ecr describe-repositories --repository-names ${APP_NAME} --query 'repositories[0].repositoryUri' --output text)" >> $GITHUB_ENV

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t $ECR_URL:${IMAGE_TAG} ./app

      - name: Trivy scan (critical/high fail)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_URL }}:${{ env.IMAGE_TAG }}
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Push image
        run: |
          docker push $ECR_URL:${IMAGE_TAG}

  deploy:
    needs: build_scan_push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-oidc-deploy
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform init/plan/apply
        working-directory: terraform
        run: |
          sed -i "s/^image_tag = .*/image_tag = "${IMAGE_TAG}"/" terraform.tfvars || echo "image_tag = "${IMAGE_TAG}"" >> terraform.tfvars
          terraform init
          terraform plan -out tf.plan
          terraform apply -auto-approve tf.plan